=== Dinesh168/lab6/payment.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="company" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                            <xs:sequence>
                            <xs:element name="name" type="xs:Name"></xs:element>
                            <xs:element name="model" minOccurs='1' maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="model_name" type="xs:string"></xs:element>
                                        <xs:element name="price"><xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                            <xs:minInclusive value="1"></xs:minInclusive>
                                            <xs:maxInclusive value="20000"></xs:maxInclusive>
                                         </xs:restriction> 
                                         </xs:simpleType></xs:element>
                                     <!--   <xs:element name="Time" type = "xs:string"></xs:element>
                                        <xs:element name="date" type="xs:string"></xs:element>
                                        <xs:element name="Transcation" type="xs:anySimpleType"></xs:element> --> 
                                    </xs:sequence>
                                </xs:complexType>
                            
                            </xs:element>
                            
                            
            
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        
    </xs:element>

    
</xs:schema>

=== Dinesh168/lab6/Part1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="paymentxsl.xsl"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="payment.xsd">
    <company>
        <name>Mahindra</name>
        <model>
            <model_name>XUV300</model_name>
            <price>12000</price>
        </model>
        <model>
            <model_name>XUV500</model_name>
            <price>13000    </price>
        </model>
        <model>
            <model_name>XUV700</model_name>
            <price>15000</price>
        </model>
    </company>
    <company>
        <name>Ford</name>
        <model>
            <model_name>Mustang</model_name>
            <price>3000</price>
        </model>
        <model>
            <model_name>Endevour</model_name>
            <price>20000</price>
        </model>
        <model>
            <model_name>Endevour</model_name>
            <price>3000</price>
        </model>

    </company>

    <company>
        <name>Kia</name>
        <model>
            <model_name>Sonet</model_name>
            <price>8000</price>
        </model>
        <model>
            <model_name>Seltos</model_name>
            <price>14000</price>
        </model>
        <model>
            <model_name>Carnival</model_name>
            <price>2200</price>
        </model>
    </company>
    <company>
        <name>Tata</name>
        <model>
            <model_name>Harrier</model_name>
            <price>2100</price>
        </model>
        <model>
            <model_name>Taigo</model_name>
            <price>6000</price>
        </model>
        <model>
            <model_name>Punch</model_name>
            <price>6000</price>
        </model>
    </company>
    <company>
        <name>Huyndai</name>
        <model>
            <model_name>Creata</model_name>
            <price>15000</price>
        </model>
        <model>
            <model_name>Venue</model_name>
            <price>8000</price>
        </model>
        <model>
            <model_name>Santo</model_name>
            <price>4000</price>
        </model>
    </company>
    <company>
        <name>MarutiSuzuki</name>
        <model>
            <model_name>Vitara</model_name>
            <price>6888</price>
        </model>
        <model>
            <model_name>Gurkha</model_name>
            <price>10000</price>
        </model>
        <model>
            <model_name>Swift</model_name>
            <price>4000</price>
        </model>
    </company>
</root>
